spring:
  application:
    name: api-financas

  datasource:
    url: jdbc:postgresql://localhost:5435/bd-api-financas
    username: coti
    password: coti
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formal_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: coti
    password: coti
    virtual-host: /

server:
  port: 8083
